export interface Stock {
    stockID: string,
    stockName: string,
    cmp: number,
    marketCap: number,
    quarterlyProfit: number,
    quarterlySales: number,
    epsAnn: number,
    roe: number,
    roce: number,
    pe: number,
    industryPE: number
}

export interface CompanyOverviewData {
  Symbol: string,
  AssetType: string,
  Name: string,
  Description:  string,
  CIK: string,
  Exchange: string,
  Currency: string,
  Country: string,
  Sector: string,
  Industry: string,
  Address: string,
  FiscalYearEnd: string,
  LatestQuarter: Date,
  MarketCapitalization: number,
  EBITDA: number,
  PERatio: number,
  PEGRatio: number,
  BookValue: number,
  DividendPerShare: number,
  DividendYield: number,
  EPS: number,
  RevenuePerShareTTM: number,
  ProfitMargin: number,
  OperatingMarginTTM: number,
  ReturnOnAssetsTTM: number,
  ReturnOnEquityTTM: number,
  RevenueTTM: number,
  GrossProfitTTM: number,
  DilutedEPSTTM: number,
  QuarterlyEarningsGrowthYOY: number,
  QuarterlyRevenueGrowthYOY: number, //negative number
  AnalystTargetPrice: number,
  TrailingPE: number,
  ForwardPE: number,
  PriceToSalesRatioTTM: number,
  PriceToBookRatio: number,
  EVToRevenue: number,
  EVToEBITDA: number,
  Beta: number,
  "52WeekHigh": number,
  "52WeekLow": number,
  "50DayMovingAverage": number,
  "200DayMovingAverage": number,
  SharesOutstanding: number,
  DividendDate: Date,
  ExDividendDate: Date
}